apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: northbridge
spec:
  selector:
    app: auth-service
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: northbridge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: 891377349839.dkr.ecr.eu-west-2.amazonaws.com/northbridge-auth-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: northbridge-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              value: redis://redis:6379/0
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: northbridge-secrets
                  key: AUTH_SECRET_KEY
          resources:
            requests:
              memory: 96Mi
              cpu: 100m
            limits:
              memory: 192Mi
              cpu: 500m
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30