apiVersion: v1
kind: Namespace
metadata:
  name: northbridge
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: northbridge
spec:
  limits:
    - type: Container
      default:
        memory: 128Mi
        cpu: 250m
      defaultRequest:
        memory: 64Mi
        cpu: 100m