apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-non-root
spec:
  validationFailureAction: Enforce
  rules:
    - name: check-non-root
      match:
        any:
          - resources:
              kinds: [Pod]
              namespaces: [northbridge]
      validate:
        message: "Containers must not run as root. Set securityContext.runAsNonRoot: true and runAsUser to a non-zero UID."
        pattern:
          spec:
            containers:
              - securityContext:
                  runAsNonRoot: true
                  runAsUser: ">0"
